name: baganbilash
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  get: 4.6.6
  image_picker:
  flutter_tflite: ^1.0.1
#  tflite_flutter: ^0.10.3
  camera: ^0.10.5+5
#  firebase_core: ^2.19.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
#  change_app_package_name: ^1.1.0
#  flutter_launcher_icons: ^0.13.1

#  firebase_database: ^10.3.1

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/ic_launcher.png"


flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/medicine/
    - assets/PlantsRog/labels.txt
    - assets/PlantsRog/model_unquant.tflite